Torus-locale/locales-account-menu.json
Torus-locale/locales-wallet-home.json

https://github.com/torusresearch/torus-website/pull/2190

additional error wallet connect

---

Torus-locale/locales-wallet-home.json

allows changing wallet name for clients

connected to wallet

---

Casper-locale/locales-wallet-dapp.json
Openlogin-locale/locales-login.json
Solana-locale/locales-wallet-dapp.json
Torus-locale/locales-login.json

custom loader message

---

Auth-service-locale/locales-common.json

https://toruslabs.atlassian.net/browse/PD-3189

remove unused t&c and privacy policy locales

---

Auth-service-locale/locales-common.json
Auth-service-locale/locales-login.json

https://toruslabs.atlassian.net/browse/PD-2801
Adds locales for this PR https://github.com/Web3Auth/auth-service/pull/66

Add auth services manage mfa locales

---

Auth-service-locale/locales-common.json
Auth-service-locale/locales-login.json
Auth-service-locale/locales-safe.json
Openlogin-locale/locales-common.json
Openlogin-locale/locales-login.json
Openlogin-locale/locales-nav.json
Openlogin-locale/locales-passwordless.json
Openlogin-locale/locales-wallet-account.json
Openlogin-locale/locales-wallet-apps.json
Openlogin-locale/locales-wallet-home.json
Openlogin-locale/locales-webauthn.json
Web3Auth-locale/locale-common.json

Turkish localization added for specifically Auth-service-locale, web3auth-locale and openlogin-locale folders.

Turkish localization added 

---

Web3Auth-locale/locale-common.json

Changes includes
- self custody via in footer
- view more options to view more, and similarly for view less

Update Web3Auth modal locales to latest design system

---

Wallet-service-locale/locales-portfolio.json

Contract Interaction
Contract Deployment
Approved {0}
Sent {0}
Received {0}

Added activity actions

---

Auth-service-locale/locales-common.json

https://toruslabs.atlassian.net/browse/PD-2484 -> locales

optional device share

---

Wallet-service-locale/locales-portfolio.json

copyPrivateKey

---

Web3Auth-locale/locale-common.json

no external wallet

---

Web3Auth-locale/locale-common.json

Jira Link: https://toruslabs.atlassian.net/browse/PD-3811
Add locales regarding passwordless input invalid input errors e.g. for phone input/email input

Add passwordless input error messages

---

Auth-service-locale/locales-common.json

Update password requirement
Jira Link:

update password requirement

---

Web3Auth-locale/locale-common.json

Add locales for external wallets in web3auth web sdk
Jira Link: https://toruslabs.atlassian.net/browse/PD-3691

add locales for wallet discovery in web3auth sdk

---

Wallet-service-locale/locales-portfolio.json

Added Submit translation for Transfer Token Submit
Jira Link:

Add submit to translations

---

Web3Auth-locale/locale-common.json

Jira Link: https://toruslabs.atlassian.net/browse/PD-3839
- Updated the Text from 'Connect with wallet' -> 'Continue with wallet'

locales fix

---

Web3Auth-locale/locale-common.json

Jira Link: https://toruslabs.atlassian.net/browse/PD-3839
changes updated for web3auth-web

v9 modal qr code copy change

---

Wallet-service-locale/locales-swap.json

Added swap locales needed for wallet services
Jira Link:
https://toruslabs.atlassian.net/browse/PD-3723?atlOrigin=eyJpIjoiNGRmODA2NTQ1MmJlNDEwZTk1Y2M1YWUwZTA5MGFiMzYiLCJwIjoiaiJ9
Wallet Service PR:
https://github.com/Web3Auth/wallet-services/pull/425

added swap locales

---

Auth-dashboard-locale/locales-wallet-account.json

password length

---

Auth-dashboard-locale/locales-common.json

update some old translations

---

Auth-dashboard-locale/locales-common.json
Auth-dashboard-locale/locales-wallet-account.json

- Delete password locale

---

Auth-dashboard-locale/locales-common.json
Auth-dashboard-locale/locales-wallet-account.json

Delete social share

---

Wallet-service-locale/locales-swap.json

Added swap locales for approving token
Jira Link:
https://toruslabs.atlassian.net/browse/PD-3723?atlOrigin=eyJpIjoiNGRmODA2NTQ1MmJlNDEwZTk1Y2M1YWUwZTA5MGFiMzYiLCJwIjoiaiJ9

approve swap locales

---

Auth-dashboard-locale/locales-wallet-account.json

added loader for passkey authenticator and devices

---

Wallet-service-locale/locales-portfolio.json

Locale will be used on swap feature
Feature PR Link:
https://github.com/Web3Auth/wallet-services/pull/479

feature not allowed on current network

---

Wallet-service-locale/locales-swap.json

added locales needed for 
https://github.com/Web3Auth/wallet-services/pull/482
Jira Link:

failed to fetch quote

---

Auth-dashboard-locale/locales-wallet-account.json

connected account tooltip

---

Openlogin-locale/locales-passwordless.json

Jira Link:https://toruslabs.atlassian.net/browse/PD-4070
- korean passwordless loclaes fix

korean passwordless loclaes fix

---

Wallet-service-locale/locales-swap.json

Jira Link: https://toruslabs.atlassian.net/browse/PD-4077
- Swap Loacle Fix

swap local fix

---

Wallet-service-locale/locales-swap.json

Jira Link: https://toruslabs.atlassian.net/browse/PD-4077
- Swap Config Tooltip Loacle added

swap tooltip locales

---

Demo-locale/locales-common.json

Jira Link: https://toruslabs.atlassian.net/browse/PD-4096
- locales added for disabled btn tooltip
- [ x] My code follows the code style of this project. (run lint)

locales added for disabled btn tooltip

---

Demo-locale/locales-common.json

Jira Link: https://toruslabs.atlassian.net/browse/PD-4096
- tooltip locale fix

tooltip locale fix

---

Wallet-service-locale/locales-portfolio.json

Wallet Service Account abstraction: Update UI for Address, and export
Jira Link:
https://toruslabs.atlassian.net/browse/PD-4229

Wallet Service Account abstraction: Update UI for Address, and export

---

Auth-dashboard-locale/locales-wallet-account.json

Change Weak Security desc to `Your account currently has no recovery factor set up. Enable MFA to secure your account and add recovery options.`
Jira Link:
https://toruslabs.atlassian.net/browse/PD-4170?atlOrigin=eyJpIjoiNDlkNDIzODRhZTEwNDViMzg1Njc3OGM2MmNiNjVkYWUiLCJwIjoiaiJ9

change desc

---

Auth-dashboard-locale/locales-wallet-account.json

Add locales for 
https://github.com/Web3Auth/auth-dashboard/pull/21
Jira Link:

add auth-dashboard no-mfa

---

Wallet-service-locale/locales-portfolio.json

Add a note when sending first transaction on confirm transaction screen
Jira Link:
https://toruslabs.atlassian.net/browse/PD-4261

First transaction note

---

Openlogin-locale/locales-passwordless.json

Adds passwordless error code.
Adds passwordless error code.

passwordless error code

---

Auth-dashboard-locale/locales-common.json
Wallet-service-locale/locales-portfolio.json

- wallet service send all
- auth-dashboard devices
Wallet Service PR
https://github.com/Web3Auth/wallet-services/pull/537
Jira Link:

Wallet Service and Auth Dashboard changes

---

Demo-locale/locales-common.json

Jira Link:https://toruslabs.atlassian.net/browse/PD-4341
- Manage MFA text

manage-mfa changes

---

Wallet-service-locale/locales-wallet-frontend.json

Add translations for WS Solana

add translations for ws-solana

---

Wallet-service-locale/locales-wallet-frontend.json

Jira Link:
Add missing translations for Solana WS

add missing locales of WS Solana

---

Auth-dashboard-locale/locales-common.json

Jira Link:
https://toruslabs.atlassian.net/browse/PD-4411

Auth-dashboard - add apply changes

---

Wallet-service-locale/locales-portfolio.json

Jira Link:
Add translation for temp api disabled in portfolio

add portfolio temp api disabled locale

---

Web3Auth-locale/locale-common.json

Jira Link: https://toruslabs.atlassian.net/browse/PD-4057
- added missing locales for React 19 Modal

React 19 Modal locales

---

Dashboard-locale/locales-whitelabel.json

Jira Link: https://toruslabs.atlassian.net/browse/PD-3584
- Add locales related to whitelabel customisation
- Only added new keys without removing old so merging to main wont affect existing dashboard whitelabel section

Dashboard branding locales (backwards compatible)

---

Web3Auth-locale/locale-common.json

Jira Link: https://toruslabs.atlassian.net/browse/PD-4498
- Adds locales
Developer tested this

Adds locales for passwordless login

---

Web3Auth-locale/locale-common.json

Jira Link:https://toruslabs.atlassian.net/browse/PD-4133

locales for react 19 modal

---

Web3Auth-locale/locale-common.json

Jira Link: https://toruslabs.atlassian.net/browse/PD-4521

locale update

---

Dashboard-locale/locales-whitelabel.json

Jira Link: https://toruslabs.atlassian.net/browse/PD-4535

Dashboard locales: replace "or" with "/" for email/telephone

---

Dashboard-locale/locales-whitelabel.json

Jira Link: https://toruslabs.atlassian.net/browse/PD-4596

add dashboard locales for wallet ui

---

Dashboard-locale/locales-whitelabel.json

Jira Link: https://toruslabs.atlassian.net/browse/PD-4596

Dashboard: add show all tokens locale

---

Wallet-service-locale/locales-portfolio.json

Jira Link: https://toruslabs.atlassian.net/browse/PD-4220
- add locales

add translations for paymaster sponsorship

---

Dashboard-locale/locales-whitelabel.json

Jira Link: https://toruslabs.atlassian.net/browse/PD-4690

Rebrand manage keys tnc locale from web3auth to consensys

---

Torus-locale/locales-login.json

Jira Link:
https://www.figma.com/design/3p3IoglxHHlry87ojz8htF/%F0%9F%9F%A2-Torus-Wallet-v2?node-id=5657-2304&t=FXCGisqdgUktefRe-4

Added locale for deprecation alert

---

Openlogin-locale/locales-passwordless.json
Web3Auth-locale/locale-common.json

Jira Link: https://consensyssoftware.atlassian.net/browse/W3APD-4282
Add test account invalid email flow type and invalid email locales for web3auth web and passwordless frontend

Add test account locales

---

Wallet-service-locale/locales-wallet-frontend.json

Locales for https://github.com/Web3Auth/wallet-services/pull/663
Jira Link:

Feat: ws login slides
